### ISSUE TITLE
Redirect is not deleted if still in trash

### ISSUE THREAD

**Issue by rebeccahum** [Automattic/WPCOM-Legacy-Redirector#29]
If we delete the redirect with `wp_delete_post( WPCOM_Legacy_Redirector::get_redirect_post_id( '/<redirect>' ) );`, it still redirects from the trash, unless you force delete via `wp_delete_post( WPCOM_Legacy_Redirector::get_redirect_post_id( '/<redirect>' ), true );`.

**Comment by senadir** [comment]
fixed it in #30

**Comment by GaryJones** [comment]
I'm not seeing this behaviour.

Since WP 4.5, trashed posts have had their post_name appended with `__trashed` ([#11863](https://core.trac.wordpress.org/ticket/11863)). This is what happens when deleting from the new UI. Since the `post_name` is different, the lookup fails and the redirect doesn't get actioned.

When doing `wp_trash_post( WPCOM_Legacy_Redirector::get_redirect_post_id( '/<redirect>' ) );`, I see the same `__trashed` get added.

When doing `wp_delete_post( WPCOM_Legacy_Redirector::get_redirect_post_id( '/<redirect>' ) );` or `wp_delete_post( WPCOM_Legacy_Redirector::get_redirect_post_id( '/<redirect>' ), false );`, I'm seeing that the post gets deleted immediately.

@rebeccahum Can you please confirm if you still see this as an issue?

**Comment by rebeccahum** [comment]
This is no longer an issue anymore because `get_redirect_post_id()` does not return an ID due to the aforementioned.  Closing now.
