### ISSUE TITLE
"Add Redirect" button in All Redirects page

### ISSUE THREAD

**Issue by davidsword** [Automattic/WPCOM-Legacy-Redirector#39]
I think a "Add Redirect" or "Add New" button in the All Redirects page, beside the header would be more consistent with default WP

![screen shot 2018-12-06 at 2 44 00 pm](https://user-images.githubusercontent.com/1996370/49616418-99136b80-f965-11e8-9e46-8d48d65fa862.png)

**Comment by GaryJones** [comment]
The current approach to the admin page with the table, is that we don't filter or change any of the markup - it's all what WP core outputs for a CPT by default.

Adding in any Add New button would be hacky.

I'm closing this in favour of handling this properly by building out the Add New page in the right way (#66), since WP will then add the Add New button on the lists page automatically.
