### ISSUE TITLE
UI: duplicate redirects when using slug and ID

### ISSUE THREAD

**Issue by GaryJones** [Automattic/WPCOM-Legacy-Redirector#53]
It's possible to get duplicate redirects:

1. Add FROM: `/redirect-to-slug`, TO: `/about`
2. Add FROM: `/redirect-to-slug`, TO: `1545` (on my test site, this is the ID of the `about` page.

The result is duplicate redirects with the same FROM but different TO:

<img width="795" alt="Screenshot 2019-05-23 at 11 12 22" src="https://user-images.githubusercontent.com/88371/58245032-c4d7b180-7d4b-11e9-9fe0-31645cd073da.png">

There should be some logic which consolidates these.

**Comment by bdtech** [comment]
Hi, @GaryJones Could you expand on how you'd like to see them consolidated? Previously an error would be displayed mentioning that a redirect already existed (if the "redirect from" was already in use). 

Would the new redirect replacing the previous be a viable solution? Otherwise, this could be a feature of edit existing redirect functionality.

**Comment by GaryJones** [comment]
> Previously an error would be displayed mentioning that a redirect already existed (if the "redirect from" was already in use).

Right - that doesn't seem to be happening when using a slug and an ID.

> Would the new redirect replacing the previous be a viable solution? Otherwise, this could be a feature of edit existing redirect functionality.

No, since that would delete the previous TO, without the user having a chance to stop it. I need to check how it detects there's an existing match for the FROM, as that seems to be missing something.

**Comment by GaryJones** [comment]
Closed with #61.
